import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import {
  ClerkProvider,
  SignedIn,
  UserButton
} from '@clerk/nextjs'

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col font-[family-name:var(--font-geist-sans)]`}
        >
          <SignedIn>
            <header className="bg-gray-800">
              <div className="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8 flex h-16 items-center">
                <UserButton />
              </div>
            </header>
          </SignedIn>
          <div className="flex-1 flex flex-col">
            {children}
          </div>
          <SignedIn>
            <footer className="bg-gray-800">
              <div className="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8 flex h-16 items-center">
                <span className="text-white">
                  © {new Date().getFullYear()} Swatt Lasagna Internal Tool. All rights reserved.
                </span>
              </div>
            </footer>
          </SignedIn>
        </body>
      </html>
    </ClerkProvider>
  );
}
